// IMPORT ALL ENV VARIABLES IN THE IMPORT STATEMENT
import { PG_URI, API_KEY, IOS_CLIENT_ID } from '@env';

// EXPORT ALL ENV VARIABLES IN THE IMPORT STATEMENT
export default {
  PG_URI,
  API_KEY,
  IOS_CLIENT_ID,
};
